apiVersion: v1
kind: ConfigMap
metadata:
  name: cezzis-cocktails-extraction-agent-config
  namespace: cezzis
  labels:
    app.kubernetes.io/part-of: cezzis
    app.kubernetes.io/managed-by: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "100"
data:
  ENV: "loc"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector.elastic-platform.svc.cluster.local:4318"
  OTEL_SERVICE_NAME: "cocktails-ingestion-extraction-agent"
  OTEL_SERVICE_NAMESPACE: "cezzis"
  OTEL_ENABLE_CONSOLE_LOGGING: "true"
  OTEL_ENABLE_TRACING: "true"
  OTEL_ENABLE_LOGGING: "true"
  KAFKA_BOOTSTRAP_SERVERS: "kafka-broker-1.kafka-platform.svc.cluster.local:19092,kafka-broker-2.kafka-platform.svc.cluster.local:19093,kafka-broker-3.kafka-platform.svc.cluster.local:19095"
  KAFKA_CONSUMER_GROUP: "cocktails-ingestion-extraction-agent"
  EXTRACTION_AGENT_ENABLED: "true"
  EXTRACTION_AGENT_KAFKA_TOPIC_NAME: "cocktails-update-topic-loc"
  EXTRACTION_AGENT_KAFKA_NUM_CONSUMERS: "1"
  EXTRACTION_AGENT_KAFKA_RESULTS_TOPIC_NAME: "cocktails-ingestion-extraction-results-loc"
  EXTRACTION_AGENT_KAFKA_MAX_POLL_INTERVAL_MS: "1500000"
  EXTRACTION_AGENT_KAFKA_AUTO_OFFSET_RESET: "earliest"
  EXTRACTION_AGENT_LLM_MODEL: "gemma4:31b"
  EXTRACTION_AGENT_LLM_MODEL_TEMPERATURE: "0.0"
  EXTRACTION_AGENT_LLM_MODEL_NUM_CTX: "8196"
  EXTRACTION_AGENT_LLM_MODEL_DISABLE_STREAMING: "true"
  EXTRACTION_AGENT_LLM_MODEL_NUM_PREDICT: "-1"
  EXTRACTION_AGENT_LLM_MODEL_LOG_VERBOSE: "false"
  EXTRACTION_AGENT_LLM_MODEL_TIMEOUT_SECONDS: "60"
  EXTRACTION_AGENT_LLM_MODEL_REASONING: "false"
  EXTRACTION_AGENT_LLM_MCP_URL: "http://cezzis-com-cocktails-mcp.cezzis.svc.cluster.local:7999/mcp/v1/mcp"
  EXTRACTION_AGENT_LLM_MCP_TRANSPORT: "streamable_http"
  EXTRACTION_AGENT_USE_LLM: "true"
  LLM_HOST: "http://ollama-host.ai-platform.svc.cluster.local:11434"
  LANGFUSE_PUBLIC_KEY: "pk-lf-2a7a9459-d479-4f71-a904-48fe1e541675"
  LANGFUSE_BASE_URL: "https://us.cloud.langfuse.com"

