apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cezzis-cocktails-extraction-agent-shared-secrets
  namespace: cezzis
  labels:
    app.kubernetes.io/part-of: cezzis
    app.kubernetes.io/managed-by: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "100"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: shared-prm-secret-store
    kind: SecretStore
  target:
    name: cezzis-cocktails-extraction-agent-shared-secrets
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        OTEL_OTLP_AUTH_HEADER: "Bearer {{ .otelApiKey }}"
        LANGFUSE_SECRET_KEY: "{{ .langfuseSecretKey }}"
        EXTRACTION_AGENT_LLM_MCP_XKEY: "na"
  data:
    - secretKey: otelApiKey
      remoteRef:
        key: otel-collector-api-key
    - secretKey: langfuseSecretKey
      remoteRef:
        key: langfuse-secret-key
