# generated by datamodel-codegen:
#   filename:  http://localhost:8011/openapi.json
#   timestamp: 2026-02-08T02:51:05+00:00

from __future__ import annotations

from enum import Enum
from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field


class CocktailDataIncludeModel(Enum):
    """
    The types of cocktail data to include in the search results.
    """

    mainImages = "mainImages"
    searchTiles = "searchTiles"
    descriptiveTitle = "descriptiveTitle"


class CocktailDescriptionChunk(BaseModel):
    """
    Model representing a chunk of cocktail description text, categorized for embedding and vector search.
    """

    category: str = Field(
        ...,
        description="Category of the description chunk",
        examples=["desc", "ingredients", "preparation"],
        title="Category",
    )
    content: str = Field(
        ...,
        description="Textual content of the description chunk",
        examples=[
            "A refreshing cocktail made with rum, lime juice, and mint leaves.",
            "Ingredients: 2 oz white rum, 1 oz lime juice, 2 tsp sugar, mint leaves, soda water.",
            "Preparation: Muddle mint leaves with sugar and lime juice. Add rum and ice, then top with soda water. Garnish with a sprig of mint.",
        ],
        title="Content",
    )


class CocktailKeywords(BaseModel):
    """
    Keyword metadata for Qdrant payload filtering. Not returned in search responses.
    """

    keywordsBaseSpirit: Optional[List[str]] = Field(
        None,
        description="Base spirit keywords (e.g. gin, rum, bourbon)",
        examples=[["gin"], ["rum"], ["bourbon"]],
        title="Keywordsbasespirit",
    )
    keywordsSpiritSubtype: Optional[List[str]] = Field(
        None,
        description="Spirit subtype keywords (e.g. aged-rum, islay-scotch)",
        examples=[["aged-rum"], ["islay-scotch"]],
        title="Keywordsspiritsubtype",
    )
    keywordsFlavorProfile: Optional[List[str]] = Field(
        None,
        description="Flavor profile keywords (e.g. bitter, sweet, citrus)",
        examples=[["bitter"], ["sweet"], ["citrus"]],
        title="Keywordsflavorprofile",
    )
    keywordsCocktailFamily: Optional[List[str]] = Field(
        None,
        description="Cocktail family keywords (e.g. sour, tiki, negroni)",
        examples=[["sour"], ["tiki"], ["negroni"]],
        title="Keywordscocktailfamily",
    )
    keywordsTechnique: Optional[List[str]] = Field(
        None,
        description="Technique keywords (e.g. shaken, stirred, built)",
        examples=[["shaken"], ["stirred"], ["built"]],
        title="Keywordstechnique",
    )
    keywordsStrength: Optional[str] = Field(
        "",
        description="Strength keyword (light, medium, strong)",
        examples=["light", "medium", "strong"],
        title="Keywordsstrength",
    )
    keywordsTemperature: Optional[str] = Field(
        "",
        description="Temperature keyword (cold, frozen, warm)",
        examples=["cold", "frozen", "warm"],
        title="Keywordstemperature",
    )
    keywordsSeason: Optional[List[str]] = Field(
        None,
        description="Season keywords (e.g. summer, winter, all-season)",
        examples=[["summer"], ["winter"], ["all-season"]],
        title="Keywordsseason",
    )
    keywordsOccasion: Optional[List[str]] = Field(
        None,
        description="Occasion keywords (e.g. aperitif, party, brunch)",
        examples=[["aperitif"], ["party"], ["brunch"]],
        title="Keywordsoccasion",
    )
    keywordsMood: Optional[List[str]] = Field(
        None,
        description="Mood keywords (e.g. sophisticated, fun, refreshing)",
        examples=[["sophisticated"], ["fun"], ["refreshing"]],
        title="Keywordsmood",
    )
    keywordsSearchTerms: Optional[List[str]] = Field(
        None,
        description="Additional search terms",
        examples=[["classic"], ["modern"], ["trending"]],
        title="Keywordssearchterms",
    )


class CocktailVectorSearchResult(BaseModel):
    """
    Model representing an individual search result from a cocktail vector search, including the score and associated metadata.
    """

    score: float = Field(
        ...,
        description="Score of the search result",
        examples=[0.5158496],
        title="Score",
    )


class GlasswareTypeModel(Enum):
    """
    The types of glassware used for serving cocktails.
    """

    none = "none"
    rocks = "rocks"
    highball = "highball"
    shotGlass = "shotGlass"
    coupe = "coupe"
    copperMug = "copperMug"
    collins = "collins"
    cocktailGlass = "cocktailGlass"
    wineGlass = "wineGlass"
    flute = "flute"
    lowball = "lowball"
    fizz = "fizz"
    tikiMug = "tikiMug"
    pintGlass = "pintGlass"
    julepTin = "julepTin"
    doubleRocks = "doubleRocks"
    hurricane = "hurricane"
    hollowedPineapple = "hollowedPineapple"
    snifter = "snifter"
    scorpionBowl = "scorpionBowl"


class HealthCheckRs(BaseModel):
    status: str = Field(..., title="Status")
    version: Optional[str] = Field(None, title="Version")
    output: Optional[str] = Field(None, title="Output")
    details: Optional[Dict[str, Any]] = Field(None, title="Details")


class IngredientApplicationTypeModel(Enum):
    """
    The application types for cocktail ingredients.
    """

    base = "base"
    additional = "additional"
    garnishment = "garnishment"
    muddle = "muddle"


class IngredientRequirementTypeModel(Enum):
    """
    The requirement types for cocktail ingredients.
    """

    none = "none"
    optional = "optional"
    required = "required"


class IngredientTypeModel(Enum):
    """
    The types of ingredients used in cocktails.
    """

    herb = "herb"
    fruit = "fruit"
    juice = "juice"
    bitters = "bitters"
    syrup = "syrup"
    protein = "protein"
    flowers = "flowers"
    sauce = "sauce"
    vegetable = "vegetable"
    dilution = "dilution"
    beer = "beer"
    spirit = "spirit"
    liqueur = "liqueur"
    wine = "wine"
    champagne = "champagne"


class PreparationTypeModel(Enum):
    """
    The preparation types for cocktail ingredients.
    """

    none = "none"
    chilled = "chilled"
    freshlySqueezed = "freshlySqueezed"
    peeledAndJuiced = "peeledAndJuiced"
    freshlyGrated = "freshlyGrated"
    quartered = "quartered"
    freshPressed = "freshPressed"


class ProblemDetails(BaseModel):
    """
    RFC 7807 compliant problem details model.

    This model provides a standard way to carry machine-readable details
    of errors in HTTP response bodies.
    """

    type: Optional[str] = Field(
        "about:blank",
        description="A URI reference that identifies the problem type",
        title="Type",
    )
    title: str = Field(
        ...,
        description="A short, human-readable summary of the problem type",
        title="Title",
    )
    status: int = Field(
        ...,
        description="The HTTP status code generated by the origin server",
        title="Status",
    )
    detail: Optional[str] = Field(
        None,
        description="A human-readable explanation specific to this occurrence of the problem",
        title="Detail",
    )
    instance: Optional[str] = Field(
        None,
        description="A URI reference that identifies the specific occurrence of the problem",
        title="Instance",
    )
    errors: Optional[Dict[str, List[str]]] = Field(
        None,
        description="A dictionary of validation errors, where keys are field names and values are lists of error messages",
        title="Errors",
    )
    extensions: Optional[Dict[str, Any]] = Field(
        None,
        description="Additional extension members for problem-specific information",
        title="Extensions",
    )


class UofMTypeModel(Enum):
    """
    The unit of measurment types for cocktail ingredients.
    """

    none = "none"
    ounces = "ounces"
    dashes = "dashes"
    tablespoon = "tablespoon"
    topoff = "topoff"
    item = "item"
    teaspoon = "teaspoon"
    toTaste = "toTaste"
    barspoon = "barspoon"
    cups = "cups"
    splash = "splash"
    discretion = "discretion"


class CocktailSearchStatistics(BaseModel):
    """
    Model representing the search statistics for a cocktail search operation, including score metrics and hit details.
    """

    totalScore: float = Field(
        ...,
        description="Sum of all hit scores",
        examples=[3.72682033],
        title="Totalscore",
    )
    maxScore: Optional[float] = Field(
        0.0,
        description="Highest individual chunk score",
        examples=[0.5158496],
        title="Maxscore",
    )
    avgScore: Optional[float] = Field(
        0.0,
        description="Average score across all hits",
        examples=[0.4815899],
        title="Avgscore",
    )
    weightedScore: Optional[float] = Field(
        0.0,
        description="Weighted score combining avg with hit count boost",
        examples=[0.6260669],
        title="Weightedscore",
    )
    hitCount: Optional[int] = Field(0, description="Number of matching chunks", examples=[3], title="Hitcount")
    hitResults: Optional[List[CocktailVectorSearchResult]] = Field(
        [],
        description="List of hit results with their scores",
        examples=[{"score": 0.5158496}, {"score": 0.4789201}, {"score": 0.45}],
        title="Hitresults",
    )


class IngredientModel(BaseModel):
    """
    Model representing an ingredient used in a cocktail, including its name, unit of measure, requirement type, preparation, and suggestions.
    """

    name: str = Field(
        ...,
        description="Name of the ingredient",
        examples=["Blanco Tequila"],
        title="Name",
    )
    uoM: UofMTypeModel = Field(..., description="Unit of Measure for the ingredient", examples=["ounces"])
    requirement: IngredientRequirementTypeModel = Field(
        ..., description="Requirement type for the ingredient", examples=["required"]
    )
    display: str = Field(
        ...,
        description="Display string for the ingredient",
        examples=["1 1/2 oz Blanco Tequila"],
        title="Display",
    )
    units: float = Field(..., description="Quantity of the ingredient", examples=[1.5], title="Units")
    preparation: PreparationTypeModel = Field(
        ..., description="Preparation type for the ingredient", examples=["chilled"]
    )
    suggestions: str = Field(
        ...,
        description="Suggestions for the ingredient",
        examples=["Use a good quality Blanco Tequila for the best flavor"],
        title="Suggestions",
    )
    types: List[IngredientTypeModel] = Field(
        ...,
        description="List of ingredient types",
        examples=[["spirit"]],
        title="Types",
    )
    applications: List[IngredientApplicationTypeModel] = Field(
        ...,
        description="List of ingredient applications",
        examples=[["base"]],
        title="Applications",
    )


class CocktailEmbeddingModel(BaseModel):
    """
    Model representing the cocktail embedding data structure used for vector search and storage.
    """

    id: str = Field(
        ...,
        description="Unique identifier for the cocktail",
        examples=["old-fashioned"],
        title="Id",
    )
    title: str = Field(
        ...,
        description="Title of the cocktail",
        examples=["Old Fashioned"],
        title="Title",
    )
    descriptiveTitle: str = Field(
        ...,
        description="Descriptive title of the cocktail",
        examples=["The Old Fashioned: A Timeless Whiskey Cocktail"],
        title="Descriptivetitle",
    )
    rating: float = Field(..., description="Rating of the cocktail", examples=[4.5], title="Rating")
    ingredients: List[IngredientModel] = Field(
        ..., description="List of ingredients in the cocktail", title="Ingredients"
    )
    isIba: bool = Field(
        ...,
        description="Indicates if the cocktail is an IBA official cocktail",
        examples=[True],
        title="Isiba",
    )
    serves: int = Field(..., description="Number of servings", examples=[1], title="Serves")
    prepTimeMinutes: int = Field(
        ...,
        description="Preparation time in minutes",
        examples=[5],
        title="Preptimeminutes",
    )
    searchTiles: List[str] = Field(
        ...,
        description="Search tiles associated with the cocktail",
        examples=["http://localhost:7179/api/v1/images/old-fashioned-cocktail-300x300.webp"],
        title="Searchtiles",
    )
    glassware: List[GlasswareTypeModel] = Field(
        ...,
        description="List of glassware types used for the cocktail",
        examples=["rocks", "coupe", "cocktailGlass"],
        title="Glassware",
    )


class CocktailEmbeddingRq(BaseModel):
    """
    Request model for embedding cocktail description chunks into the vector database.
    """

    contentChunks: List[CocktailDescriptionChunk] = Field(
        ..., description="List of text chunks to be embedded", title="Contentchunks"
    )
    cocktailEmbeddingModel: CocktailEmbeddingModel = Field(
        ..., description="Cocktail embedding model associated with the chunks"
    )
    cocktailKeywords: Optional[CocktailKeywords] = Field(
        None, description="Keyword metadata for Qdrant payload filtering"
    )


class CocktailModel(BaseModel):
    """
    Model representing the cocktail data structure used for vector search and storage.
    """

    id: str = Field(
        ...,
        description="Unique identifier for the cocktail",
        examples=["old-fashioned"],
        title="Id",
    )
    title: str = Field(
        ...,
        description="Title of the cocktail",
        examples=["Old Fashioned"],
        title="Title",
    )
    descriptiveTitle: str = Field(
        ...,
        description="Descriptive title of the cocktail",
        examples=["The Old Fashioned: A Timeless Whiskey Cocktail"],
        title="Descriptivetitle",
    )
    rating: float = Field(..., description="Rating of the cocktail", examples=[4.5], title="Rating")
    ingredients: List[IngredientModel] = Field(
        ..., description="List of ingredients in the cocktail", title="Ingredients"
    )
    isIba: bool = Field(
        ...,
        description="Indicates if the cocktail is an IBA official cocktail",
        examples=[True],
        title="Isiba",
    )
    serves: int = Field(..., description="Number of servings", examples=[1], title="Serves")
    prepTimeMinutes: int = Field(
        ...,
        description="Preparation time in minutes",
        examples=[5],
        title="Preptimeminutes",
    )
    searchTiles: List[str] = Field(
        ...,
        description="Search tiles associated with the cocktail",
        examples=["http://localhost:7179/api/v1/images/old-fashioned-cocktail-300x300.webp"],
        title="Searchtiles",
    )
    glassware: List[GlasswareTypeModel] = Field(
        ...,
        description="List of glassware types used for the cocktail",
        examples=["rocks", "coupe", "cocktailGlass"],
        title="Glassware",
    )
    searchStatistics: Optional[CocktailSearchStatistics] = Field(None, description="Search statistics for the cocktail")


class CocktailsSearchRs(BaseModel):
    """
    Model representing the response structure for a cocktail search operation, containing a list of matching cocktails.
    """

    items: List[CocktailModel] = Field(..., description="List of cocktails returned from the search", title="Items")
