# generated by datamodel-codegen:
#   filename:  http://localhost:8011/openapi.json
#   timestamp: 2025-12-29T19:33:18+00:00

from __future__ import annotations

from enum import Enum
from typing import List, Optional, Union

from pydantic import BaseModel, Field


class CocktailDataIncludeModel(Enum):
    mainImages = "mainImages"
    searchTiles = "searchTiles"
    descriptiveTitle = "descriptiveTitle"


class CocktailDescriptionChunk(BaseModel):
    category: str = Field(..., description="Category of the description chunk", title="Category")
    content: str = Field(..., description="Textual content of the description chunk", title="Content")


class GlasswareTypeModel(Enum):
    none = "none"
    rocks = "rocks"
    highball = "highball"
    shotGlass = "shotGlass"
    coupe = "coupe"
    copperMug = "copperMug"
    collins = "collins"
    cocktailGlass = "cocktailGlass"
    wineGlass = "wineGlass"
    flute = "flute"
    lowball = "lowball"
    fizz = "fizz"
    tikiMug = "tikiMug"
    pintGlass = "pintGlass"
    julepTin = "julepTin"
    doubleRocks = "doubleRocks"
    hurricane = "hurricane"
    hollowedPineapple = "hollowedPineapple"
    snifter = "snifter"
    scorpionBowl = "scorpionBowl"


class IngredientApplicationTypeModel(Enum):
    base = "base"
    additional = "additional"
    garnishment = "garnishment"
    muddle = "muddle"


class IngredientRequirementTypeModel(Enum):
    none = "none"
    optional = "optional"
    required = "required"


class IngredientTypeModel(Enum):
    herb = "herb"
    fruit = "fruit"
    juice = "juice"
    bitters = "bitters"
    syrup = "syrup"
    protein = "protein"
    flowers = "flowers"
    sauce = "sauce"
    vegetable = "vegetable"
    dilution = "dilution"
    beer = "beer"
    spirit = "spirit"
    liqueur = "liqueur"
    wine = "wine"
    champagne = "champagne"


class PreparationTypeModel(Enum):
    none = "none"
    chilled = "chilled"
    freshlySqueezed = "freshlySqueezed"
    peeledAndJuiced = "peeledAndJuiced"
    freshlyGrated = "freshlyGrated"
    quartered = "quartered"
    freshPressed = "freshPressed"


class UofMTypeModel(Enum):
    """
    The unit of measurment types for cocktail ingredients.
    """

    none = "none"
    ounces = "ounces"
    dashes = "dashes"
    tablespoon = "tablespoon"
    topoff = "topoff"
    item = "item"
    teaspoon = "teaspoon"
    toTaste = "toTaste"
    barspoon = "barspoon"
    cups = "cups"
    splash = "splash"
    discretion = "discretion"


class ValidationError(BaseModel):
    loc: List[Union[str, int]] = Field(..., title="Location")
    msg: str = Field(..., title="Message")
    type: str = Field(..., title="Error Type")


class HTTPValidationError(BaseModel):
    detail: Optional[List[ValidationError]] = Field(None, title="Detail")


class IngredientModel(BaseModel):
    name: str = Field(..., description="Name of the ingredient", title="Name")
    uoM: UofMTypeModel = Field(..., description="Unit of Measure for the ingredient")
    requirement: IngredientRequirementTypeModel = Field(..., description="Requirement type for the ingredient")
    display: str = Field(..., description="Display string for the ingredient", title="Display")
    units: float = Field(..., description="Quantity of the ingredient", title="Units")
    preparation: PreparationTypeModel = Field(..., description="Preparation type for the ingredient")
    suggestions: str = Field(..., description="Suggestions for the ingredient", title="Suggestions")
    types: List[IngredientTypeModel] = Field(..., description="List of ingredient types", title="Types")
    applications: List[IngredientApplicationTypeModel] = Field(
        ..., description="List of ingredient applications", title="Applications"
    )


class CocktailModelInput(BaseModel):
    id: str = Field(..., description="Unique identifier for the cocktail", title="Id")
    title: str = Field(..., description="Title of the cocktail", title="Title")
    descriptiveTitle: str = Field(..., description="Descriptive title of the cocktail", title="Descriptivetitle")
    rating: float = Field(..., description="Rating of the cocktail", title="Rating")
    ingredients: List[IngredientModel] = Field(
        ..., description="List of ingredients in the cocktail", title="Ingredients"
    )
    isIba: bool = Field(
        ...,
        description="Indicates if the cocktail is an IBA official cocktail",
        title="Isiba",
    )
    serves: int = Field(..., description="Number of servings", title="Serves")
    prepTimeMinutes: int = Field(..., description="Preparation time in minutes", title="Preptimeminutes")
    searchTiles: List[str] = Field(
        ...,
        description="Search tiles associated with the cocktail",
        title="Searchtiles",
    )
    glassware: List[GlasswareTypeModel] = Field(
        ...,
        description="List of glassware types used for the cocktail",
        title="Glassware",
    )


class CocktailModelOutput(BaseModel):
    id: str = Field(..., description="Unique identifier for the cocktail", title="Id")
    title: str = Field(..., description="Title of the cocktail", title="Title")
    descriptiveTitle: str = Field(..., description="Descriptive title of the cocktail", title="Descriptivetitle")
    rating: float = Field(..., description="Rating of the cocktail", title="Rating")
    ingredients: List[IngredientModel] = Field(
        ..., description="List of ingredients in the cocktail", title="Ingredients"
    )
    isIba: bool = Field(
        ...,
        description="Indicates if the cocktail is an IBA official cocktail",
        title="Isiba",
    )
    serves: int = Field(..., description="Number of servings", title="Serves")
    prepTimeMinutes: int = Field(..., description="Preparation time in minutes", title="Preptimeminutes")
    searchTiles: List[str] = Field(
        ...,
        description="Search tiles associated with the cocktail",
        title="Searchtiles",
    )
    glassware: List[GlasswareTypeModel] = Field(
        ...,
        description="List of glassware types used for the cocktail",
        title="Glassware",
    )


class CocktailsSearchRs(BaseModel):
    items: List[CocktailModelOutput] = Field(
        ..., description="List of cocktails returned from the search", title="Items"
    )


class CocktailEmbeddingRq(BaseModel):
    """
    Request model for embedding cocktail description chunks into the vector database.
    """

    content_chunks: List[CocktailDescriptionChunk] = Field(
        ..., description="List of text chunks to be embedded", title="Content Chunks"
    )
    cocktail_model: CocktailModelInput = Field(..., description="Cocktail model associated with the chunks")
