# generated by datamodel-codegen:
#   filename:  http://localhost:8011/openapi.json
#   timestamp: 2026-02-07T18:54:20+00:00

from __future__ import annotations

from enum import Enum
from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field


class CocktailDataIncludeModel(Enum):
    mainImages = "mainImages"
    searchTiles = "searchTiles"
    descriptiveTitle = "descriptiveTitle"


class CocktailDescriptionChunk(BaseModel):
    category: str = Field(..., description="Category of the description chunk", title="Category")
    content: str = Field(..., description="Textual content of the description chunk", title="Content")


class CocktailKeywords(BaseModel):
    """
    Keyword metadata for Qdrant payload filtering. Not returned in search responses.
    """

    keywordsBaseSpirit: Optional[List[str]] = Field(
        None,
        description="Base spirit keywords (e.g. gin, rum, bourbon)",
        title="Keywordsbasespirit",
    )
    keywordsSpiritSubtype: Optional[List[str]] = Field(
        None,
        description="Spirit subtype keywords (e.g. aged-rum, islay-scotch)",
        title="Keywordsspiritsubtype",
    )
    keywordsFlavorProfile: Optional[List[str]] = Field(
        None,
        description="Flavor profile keywords (e.g. bitter, sweet, citrus)",
        title="Keywordsflavorprofile",
    )
    keywordsCocktailFamily: Optional[List[str]] = Field(
        None,
        description="Cocktail family keywords (e.g. sour, tiki, negroni)",
        title="Keywordscocktailfamily",
    )
    keywordsTechnique: Optional[List[str]] = Field(
        None,
        description="Technique keywords (e.g. shaken, stirred, built)",
        title="Keywordstechnique",
    )
    keywordsStrength: Optional[str] = Field(
        "",
        description="Strength keyword (light, medium, strong)",
        title="Keywordsstrength",
    )
    keywordsTemperature: Optional[str] = Field(
        "",
        description="Temperature keyword (cold, frozen, warm)",
        title="Keywordstemperature",
    )
    keywordsSeason: Optional[List[str]] = Field(
        None,
        description="Season keywords (e.g. summer, winter, all-season)",
        title="Keywordsseason",
    )
    keywordsOccasion: Optional[List[str]] = Field(
        None,
        description="Occasion keywords (e.g. aperitif, party, brunch)",
        title="Keywordsoccasion",
    )
    keywordsMood: Optional[List[str]] = Field(
        None,
        description="Mood keywords (e.g. sophisticated, fun, refreshing)",
        title="Keywordsmood",
    )
    keywordsSearchTerms: Optional[List[str]] = Field(
        None, description="Additional search terms", title="Keywordssearchterms"
    )


class CocktailVectorSearchResult(BaseModel):
    score: float = Field(..., description="Score of the search result", title="Score")


class GlasswareTypeModel(Enum):
    none = "none"
    rocks = "rocks"
    highball = "highball"
    shotGlass = "shotGlass"
    coupe = "coupe"
    copperMug = "copperMug"
    collins = "collins"
    cocktailGlass = "cocktailGlass"
    wineGlass = "wineGlass"
    flute = "flute"
    lowball = "lowball"
    fizz = "fizz"
    tikiMug = "tikiMug"
    pintGlass = "pintGlass"
    julepTin = "julepTin"
    doubleRocks = "doubleRocks"
    hurricane = "hurricane"
    hollowedPineapple = "hollowedPineapple"
    snifter = "snifter"
    scorpionBowl = "scorpionBowl"


class HealthCheckRs(BaseModel):
    status: str = Field(..., title="Status")
    version: Optional[str] = Field(None, title="Version")
    output: Optional[str] = Field(None, title="Output")
    details: Optional[Dict[str, Any]] = Field(None, title="Details")


class IngredientApplicationTypeModel(Enum):
    base = "base"
    additional = "additional"
    garnishment = "garnishment"
    muddle = "muddle"


class IngredientRequirementTypeModel(Enum):
    none = "none"
    optional = "optional"
    required = "required"


class IngredientTypeModel(Enum):
    herb = "herb"
    fruit = "fruit"
    juice = "juice"
    bitters = "bitters"
    syrup = "syrup"
    protein = "protein"
    flowers = "flowers"
    sauce = "sauce"
    vegetable = "vegetable"
    dilution = "dilution"
    beer = "beer"
    spirit = "spirit"
    liqueur = "liqueur"
    wine = "wine"
    champagne = "champagne"


class PreparationTypeModel(Enum):
    none = "none"
    chilled = "chilled"
    freshlySqueezed = "freshlySqueezed"
    peeledAndJuiced = "peeledAndJuiced"
    freshlyGrated = "freshlyGrated"
    quartered = "quartered"
    freshPressed = "freshPressed"


class ProblemDetails(BaseModel):
    """
    RFC 7807 compliant problem details model.

    This model provides a standard way to carry machine-readable details
    of errors in HTTP response bodies.
    """

    type: Optional[str] = Field(
        "about:blank",
        description="A URI reference that identifies the problem type",
        title="Type",
    )
    title: str = Field(
        ...,
        description="A short, human-readable summary of the problem type",
        title="Title",
    )
    status: int = Field(
        ...,
        description="The HTTP status code generated by the origin server",
        title="Status",
    )
    detail: Optional[str] = Field(
        None,
        description="A human-readable explanation specific to this occurrence of the problem",
        title="Detail",
    )
    instance: Optional[str] = Field(
        None,
        description="A URI reference that identifies the specific occurrence of the problem",
        title="Instance",
    )
    errors: Optional[Dict[str, List[str]]] = Field(
        None,
        description="A dictionary of validation errors, where keys are field names and values are lists of error messages",
        title="Errors",
    )
    extensions: Optional[Dict[str, Any]] = Field(
        None,
        description="Additional extension members for problem-specific information",
        title="Extensions",
    )


class UofMTypeModel(Enum):
    """
    The unit of measurment types for cocktail ingredients.
    """

    none = "none"
    ounces = "ounces"
    dashes = "dashes"
    tablespoon = "tablespoon"
    topoff = "topoff"
    item = "item"
    teaspoon = "teaspoon"
    toTaste = "toTaste"
    barspoon = "barspoon"
    cups = "cups"
    splash = "splash"
    discretion = "discretion"


class CocktailSearchStatistics(BaseModel):
    total_score: float = Field(..., description="Sum of all hit scores", title="Total Score")
    max_score: Optional[float] = Field(0.0, description="Highest individual chunk score", title="Max Score")
    avg_score: Optional[float] = Field(0.0, description="Average score across all hits", title="Avg Score")
    weighted_score: Optional[float] = Field(
        0.0,
        description="Weighted score combining avg with hit count boost",
        title="Weighted Score",
    )
    hit_count: Optional[int] = Field(0, description="Number of matching chunks", title="Hit Count")
    hit_results: Optional[List[CocktailVectorSearchResult]] = Field(
        [], description="List of hit results with their scores", title="Hit Results"
    )


class IngredientModel(BaseModel):
    name: str = Field(..., description="Name of the ingredient", title="Name")
    uoM: UofMTypeModel = Field(..., description="Unit of Measure for the ingredient")
    requirement: IngredientRequirementTypeModel = Field(..., description="Requirement type for the ingredient")
    display: str = Field(..., description="Display string for the ingredient", title="Display")
    units: float = Field(..., description="Quantity of the ingredient", title="Units")
    preparation: PreparationTypeModel = Field(..., description="Preparation type for the ingredient")
    suggestions: str = Field(..., description="Suggestions for the ingredient", title="Suggestions")
    types: List[IngredientTypeModel] = Field(..., description="List of ingredient types", title="Types")
    applications: List[IngredientApplicationTypeModel] = Field(
        ..., description="List of ingredient applications", title="Applications"
    )


class CocktailModelInput(BaseModel):
    id: str = Field(..., description="Unique identifier for the cocktail", title="Id")
    title: str = Field(..., description="Title of the cocktail", title="Title")
    descriptiveTitle: str = Field(..., description="Descriptive title of the cocktail", title="Descriptivetitle")
    rating: float = Field(..., description="Rating of the cocktail", title="Rating")
    ingredients: List[IngredientModel] = Field(
        ..., description="List of ingredients in the cocktail", title="Ingredients"
    )
    isIba: bool = Field(
        ...,
        description="Indicates if the cocktail is an IBA official cocktail",
        title="Isiba",
    )
    serves: int = Field(..., description="Number of servings", title="Serves")
    prepTimeMinutes: int = Field(..., description="Preparation time in minutes", title="Preptimeminutes")
    searchTiles: List[str] = Field(
        ...,
        description="Search tiles associated with the cocktail",
        title="Searchtiles",
    )
    glassware: List[GlasswareTypeModel] = Field(
        ...,
        description="List of glassware types used for the cocktail",
        title="Glassware",
    )
    search_statistics: Optional[CocktailSearchStatistics] = Field(
        None, description="Search statistics for the cocktail"
    )


class CocktailModelOutput(BaseModel):
    id: str = Field(..., description="Unique identifier for the cocktail", title="Id")
    title: str = Field(..., description="Title of the cocktail", title="Title")
    descriptiveTitle: str = Field(..., description="Descriptive title of the cocktail", title="Descriptivetitle")
    rating: float = Field(..., description="Rating of the cocktail", title="Rating")
    ingredients: List[IngredientModel] = Field(
        ..., description="List of ingredients in the cocktail", title="Ingredients"
    )
    isIba: bool = Field(
        ...,
        description="Indicates if the cocktail is an IBA official cocktail",
        title="Isiba",
    )
    serves: int = Field(..., description="Number of servings", title="Serves")
    prepTimeMinutes: int = Field(..., description="Preparation time in minutes", title="Preptimeminutes")
    searchTiles: List[str] = Field(
        ...,
        description="Search tiles associated with the cocktail",
        title="Searchtiles",
    )
    glassware: List[GlasswareTypeModel] = Field(
        ...,
        description="List of glassware types used for the cocktail",
        title="Glassware",
    )
    search_statistics: Optional[CocktailSearchStatistics] = Field(
        None, description="Search statistics for the cocktail"
    )


class CocktailsSearchRs(BaseModel):
    items: List[CocktailModelOutput] = Field(
        ..., description="List of cocktails returned from the search", title="Items"
    )


class CocktailEmbeddingRq(BaseModel):
    """
    Request model for embedding cocktail description chunks into the vector database.
    """

    content_chunks: List[CocktailDescriptionChunk] = Field(
        ..., description="List of text chunks to be embedded", title="Content Chunks"
    )
    cocktail_model: CocktailModelInput = Field(..., description="Cocktail model associated with the chunks")
    cocktail_keywords: Optional[CocktailKeywords] = Field(
        None, description="Keyword metadata for Qdrant payload filtering"
    )
