apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cezzis-cocktails-extraction-agent-loc
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    app.kubernetes.io/part-of: cezzis
spec:
  project: default
  source:
    repoURL: 'https://github.com/mtnvencenzo/cezzis-com-ingestion-agentic-wf.git'
    targetRevision: main
    path: extraction-agent/.iac/k8s-loc
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: cezzis
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=false
      - PruneLast=true