apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: cezzis-cocktails-extraction-agent-cloudsync-updater
  namespace: argocd
spec:
  applicationRefs:
    - namePattern: "cezzis-cocktails-extraction-agent-cloudsync"
      commonUpdateSettings:
        updateStrategy: "semver"
        forceUpdate: true
      images:
        - alias: "cocktailsingestionextractionagent"
          imageName: "acrveceusgloshared001.azurecr.io/cocktailsingestionextractionagent:0.x"
          manifestTargets:
            kustomize:
              name: "acrveceusgloshared001.azurecr.io/cocktailsingestionextractionagent"
  writeBackConfig:
    method: "git:secret:argocd/git-creds"
    gitConfig:
      branch: main
      writeBackTarget: "kustomization:/extraction-agent/.iac/k8s-cloudsync"
