# generated by datamodel-codegen:
#   filename:  http://localhost:7177/scalar/v1/openapi.json
#   timestamp: 2025-12-18T14:40:19+00:00

from __future__ import annotations

from enum import Enum
from typing import List, Optional

from pydantic import AwareDatetime, BaseModel, Field, RootModel


class AccountAddressModel(BaseModel):
    """
    The optional primary address listed with the account
    """

    addressLine1: str = Field(..., description="The primary street address.")
    addressLine2: str = Field(..., description="The secondary street address building sub divider")
    city: str = Field(..., description="The city the address is within")
    region: str = Field(..., description="The state or province")
    subRegion: str = Field(..., description="The state or province divered such as county")
    postalCode: str = Field(..., description="The postal or zip code")
    country: str = Field(..., description="The country")


class AccountCocktailRatingModel(BaseModel):
    """
    The cocktail rating values
    """

    oneStars: int = Field(..., description="The number of one star ratings", examples=["5"])
    twoStars: int = Field(..., description="The number of two star ratings", examples=["1"])
    threeStars: int = Field(..., description="The number of three star ratings", examples=["1"])
    fourStars: int = Field(..., description="The number of four star ratings", examples=["1"])
    fiveStars: int = Field(..., description="The number of five star ratings", examples=["1"])
    totalStars: int = Field(..., description="The total number of stars given", examples=["1"])
    rating: float = Field(..., description="The actual overal rating", examples=["3.5"])
    ratingCount: int = Field(..., description="The total number of ratings given", examples=["1"])


class AccountCocktailRatingsModel(BaseModel):
    cocktailId: str = Field(..., description="The cocktail identifier")
    stars: int = Field(..., description="The rating for the cocktail (1-5)")


class AccountCocktailRatingsRs(BaseModel):
    ratings: List[AccountCocktailRatingsModel] = Field(..., description="The cocktail ratings")


class ChangeAccountOwnedEmailRq(BaseModel):
    email: str = Field(..., description="The email address for the account")


class ChangeAccountOwnedPasswordRq(BaseModel):
    email: str = Field(..., description="The email address for the account")


class ChangeAccountOwnedUsernameRq(BaseModel):
    username: str = Field(..., description="The username to change to for the account")


class CocktailDataIncludeModel(Enum):
    mainImages = "mainImages"
    searchTiles = "searchTiles"
    descriptiveTitle = "descriptiveTitle"


class CocktailFavoritingActionModel(Enum):
    """
    The action to take on the cocktail within the favorites list
    """

    add = "add"
    remove = "remove"


class CocktailImageModel(BaseModel):
    uri: str = Field(
        ...,
        description="The uri of the image",
        examples=["https://cdn.cezzis.com/cocktails/traditional-clover-club-cocktail-main.webp"],
    )
    width: int = Field(..., description="The width of the image", examples=[800])
    height: int = Field(..., description="The height of the image", examples=[533])


class CocktailImageModel2(BaseModel):
    uri: str = Field(
        ...,
        description="The uri of the image",
        examples=["https://cdn.cezzis.com/cocktails/traditional-clover-club-cocktail-main.webp"],
    )
    width: int = Field(..., description="The width of the image", examples=[800])
    height: int = Field(..., description="The height of the image", examples=[533])


class CocktailRatingModel(BaseModel):
    """
    A ratings for this cocktail
    """

    oneStars: int = Field(..., description="The number of one star ratings", examples=["5"])
    twoStars: int = Field(..., description="The number of two star ratings", examples=["1"])
    threeStars: int = Field(..., description="The number of three star ratings", examples=["1"])
    fourStars: int = Field(..., description="The number of four star ratings", examples=["1"])
    fiveStars: int = Field(..., description="The number of five star ratings", examples=["1"])
    totalStars: int = Field(..., description="The total number of stars given", examples=["1"])
    rating: float = Field(..., description="The actual overal rating", examples=["3.5"])
    ratingCount: int = Field(..., description="The total number of ratings given", examples=["1"])


class CocktailRecommendationModel(BaseModel):
    """
    The cocktail recommendation model
    """

    name: str = Field(
        ...,
        description="The name of the cocktail or variation",
        examples=["Painkiller (Cezzi's Version)"],
    )
    ingredients: str = Field(
        ...,
        description="The ingredients description of the cocktail or variation",
        examples=["3 ounces pimm's no.1"],
    )
    directions: str = Field(
        ...,
        description="The directions description of the cocktail or variation",
        examples=["Pour everything into a cocktail glass and stir"],
    )


class CocktailRecommendationRq(BaseModel):
    recommendation: CocktailRecommendationModel
    verificationCode: str = Field(
        ...,
        description="The google recaptcha verification code returned after being valid",
        examples=["03AFcWeA4HedFMVgSEGAfbZXZdbLu0RXp"],
    )


class CocktailUpdatedNotificationModel(Enum):
    """
    The notification setting to use when new cocktail addtions are added
    """

    never = "never"
    always = "always"


class DisplayThemeModel(Enum):
    """
    The accessibility theme
    """

    light = "light"
    dark = "dark"


class DisplayThemeModel2(Enum):
    """
    The display theme (light, dark)
    """

    light = "light"
    dark = "dark"


class DocumentFormat(Enum):
    """
    The format that the document content is in
    """

    markdown = "markdown"


class GlasswareTypeModel(Enum):
    none = "none"
    rocks = "rocks"
    highball = "highball"
    shotGlass = "shotGlass"
    coupe = "coupe"
    copperMug = "copperMug"
    collins = "collins"
    cocktailGlass = "cocktailGlass"
    wineGlass = "wineGlass"
    flute = "flute"
    lowball = "lowball"
    fizz = "fizz"
    tikiMug = "tikiMug"
    pintGlass = "pintGlass"
    julepTin = "julepTin"
    doubleRocks = "doubleRocks"
    hurricane = "hurricane"
    hollowedPineapple = "hollowedPineapple"
    snifter = "snifter"
    scorpionBowl = "scorpionBowl"


class IFormFile(RootModel[bytes]):
    root: bytes


class IngredientApplicationModel(Enum):
    base = "base"
    additional = "additional"
    garnishment = "garnishment"
    muddle = "muddle"


class IngredientFilterModel(BaseModel):
    id: str = Field(..., description="The filter identifier", examples=["classification-name"])
    name: str = Field(..., description="The display name of the filter", examples=["Name Of Filter"])


class IngredientFilterModel10(BaseModel):
    id: str = Field(..., description="The filter identifier", examples=["classification-name"])
    name: str = Field(..., description="The display name of the filter", examples=["Name Of Filter"])


class IngredientFilterModel11(BaseModel):
    id: str = Field(..., description="The filter identifier", examples=["classification-name"])
    name: str = Field(..., description="The display name of the filter", examples=["Name Of Filter"])


class IngredientFilterModel12(BaseModel):
    id: str = Field(..., description="The filter identifier", examples=["classification-name"])
    name: str = Field(..., description="The display name of the filter", examples=["Name Of Filter"])


class IngredientFilterModel13(BaseModel):
    id: str = Field(..., description="The filter identifier", examples=["classification-name"])
    name: str = Field(..., description="The display name of the filter", examples=["Name Of Filter"])


class IngredientFilterModel2(BaseModel):
    id: str = Field(..., description="The filter identifier", examples=["classification-name"])
    name: str = Field(..., description="The display name of the filter", examples=["Name Of Filter"])


class IngredientFilterModel3(BaseModel):
    id: str = Field(..., description="The filter identifier", examples=["classification-name"])
    name: str = Field(..., description="The display name of the filter", examples=["Name Of Filter"])


class IngredientFilterModel4(BaseModel):
    id: str = Field(..., description="The filter identifier", examples=["classification-name"])
    name: str = Field(..., description="The display name of the filter", examples=["Name Of Filter"])


class IngredientFilterModel5(BaseModel):
    id: str = Field(..., description="The filter identifier", examples=["classification-name"])
    name: str = Field(..., description="The display name of the filter", examples=["Name Of Filter"])


class IngredientFilterModel6(BaseModel):
    id: str = Field(..., description="The filter identifier", examples=["classification-name"])
    name: str = Field(..., description="The display name of the filter", examples=["Name Of Filter"])


class IngredientFilterModel7(BaseModel):
    id: str = Field(..., description="The filter identifier", examples=["classification-name"])
    name: str = Field(..., description="The display name of the filter", examples=["Name Of Filter"])


class IngredientFilterModel8(BaseModel):
    id: str = Field(..., description="The filter identifier", examples=["classification-name"])
    name: str = Field(..., description="The display name of the filter", examples=["Name Of Filter"])


class IngredientFilterModel9(BaseModel):
    id: str = Field(..., description="The filter identifier", examples=["classification-name"])
    name: str = Field(..., description="The display name of the filter", examples=["Name Of Filter"])


class IngredientRequirementTypeModel(Enum):
    """
    Whether or not this ingredient is required ('Required' or 'Optional')
    """

    none = "none"
    optional = "optional"
    required = "required"


class IngredientTypeModel(Enum):
    herb = "herb"
    fruit = "fruit"
    juice = "juice"
    bitters = "bitters"
    syrup = "syrup"
    protein = "protein"
    flowers = "flowers"
    sauce = "sauce"
    vegetable = "vegetable"
    dilution = "dilution"
    beer = "beer"
    spirit = "spirit"
    liqueur = "liqueur"
    wine = "wine"
    champagne = "champagne"


class InstructionStepModel(BaseModel):
    display: str = Field(
        ...,
        description="The displayable value for the instruction step",
        examples=[
            "Combine the gin, lemon juice, raspberry syrup, and egg white in a shaker without ice and dry shake (shake without ice) for about 10 seconds to make the foam."
        ],
    )
    order: int = Field(
        ...,
        description="The order of the instruction step in which it should be performed",
        examples=[1],
    )


class LegalDocumentRs(BaseModel):
    document: str = Field(..., description="The document content")
    format: DocumentFormat


class PreparationTypeModel(Enum):
    """
    Any preparation that should be made with this ingredient
    """

    none = "none"
    chilled = "chilled"
    freshlySqueezed = "freshlySqueezed"
    peeledAndJuiced = "peeledAndJuiced"
    freshlyGrated = "freshlyGrated"
    quartered = "quartered"
    freshPressed = "freshPressed"


class ProblemDetails(BaseModel):
    type: Optional[str] = None
    title: Optional[str] = None
    status: Optional[int] = None
    detail: Optional[str] = None
    instance: Optional[str] = None


class PublishCocktailsRq(BaseModel):
    cocktailIds: List[str] = Field(
        ...,
        description="A list of cocktail IDs to publish",
        examples=[["pegu-club", "aperol-spritz", "margarita"]],
    )


class RateCocktailRq(BaseModel):
    cocktailId: str = Field(..., description="The cocktail identifier")
    stars: int = Field(..., description="The rating for the cocktail (1-5)")


class RateCocktailRs(BaseModel):
    ratings: List[AccountCocktailRatingsModel] = Field(..., description="The cocktail ratings")
    cocktailId: str = Field(..., description="The cocktail identifier")
    cocktailRating: AccountCocktailRatingModel


class UofMTypeModel(Enum):
    """
    The unit of measure when using this ingredient in a cocktail recipe
    """

    none = "none"
    ounces = "ounces"
    dashes = "dashes"
    tablespoon = "tablespoon"
    topoff = "topoff"
    item = "item"
    teaspoon = "teaspoon"
    toTaste = "toTaste"
    barspoon = "barspoon"
    cups = "cups"
    splash = "splash"
    discretion = "discretion"


class UpdateAccountOwnedAccessibilitySettingsRq(BaseModel):
    theme: DisplayThemeModel2


class UpdateAccountOwnedNotificationSettingsRq(BaseModel):
    onNewCocktailAdditions: CocktailUpdatedNotificationModel


class UpdateAccountOwnedProfileRq(BaseModel):
    givenName: str = Field(..., description="The given name on the account")
    familyName: str = Field(..., description="The family name on the account")
    displayName: str = Field(..., description="The display for the account visible to other users")
    primaryAddress: AccountAddressModel


class UploadProfileImageRs(BaseModel):
    imageUri: str = Field(..., description="The uri for the image that was uploaded")


class AccountAccessibilitySettingsModel(BaseModel):
    """
    The accessibility settings for the account
    """

    theme: DisplayThemeModel


class AccountNotificationSettingsModel(BaseModel):
    """
    The notification settings for the account
    """

    onNewCocktailAdditions: CocktailUpdatedNotificationModel


class AccountOwnedProfileRs(BaseModel):
    subjectId: str = Field(..., description="The federated subject identifier for the account")
    loginEmail: str = Field(..., description="The login email address for the account")
    email: str = Field(..., description="The email address for the account")
    givenName: str = Field(..., description="The given name on the account")
    familyName: str = Field(..., description="The family name on the account")
    avatarUri: str = Field(..., description="The avatar image uri for the account")
    primaryAddress: AccountAddressModel
    displayName: str = Field(..., description="The display name for the account visible to other users")
    accessibility: AccountAccessibilitySettingsModel
    favoriteCocktails: List[str] = Field(..., description="The list of favorite cocktails")
    notifications: AccountNotificationSettingsModel


class CocktailFavoriteActionModel(BaseModel):
    cocktailId: str = Field(..., description="The cocktail identifier")
    action: CocktailFavoritingActionModel


class CocktailIngredientFiltersRs(BaseModel):
    glassware: List[IngredientFilterModel] = Field(
        ...,
        description="The cocktail ingredient filters for searching against recommended glassware",
    )
    spirits: List[IngredientFilterModel2] = Field(
        ..., description="The cocktail ingredient filters for searching against spirits"
    )
    liqueurs: List[IngredientFilterModel3] = Field(
        ...,
        description="The cocktail ingredient filters for searching against liqueurs",
    )
    fruits: List[IngredientFilterModel4] = Field(
        ..., description="The cocktail ingredient filters for searching against friuts"
    )
    vegetables: List[IngredientFilterModel5] = Field(
        ...,
        description="The cocktail ingredient filters for searching against vegetables",
    )
    herbsAndFlowers: List[IngredientFilterModel6] = Field(
        ...,
        description="The cocktail ingredient filters for searching against herbs and flowers",
    )
    syrupsAndSauces: List[IngredientFilterModel7] = Field(
        ...,
        description="The cocktail ingredient filters for searching against syrups and sauces",
    )
    bitters: List[IngredientFilterModel8] = Field(
        ..., description="The cocktail ingredient filters for searching against bitters"
    )
    proteins: List[IngredientFilterModel9] = Field(
        ...,
        description="The cocktail ingredient filters for searching against proteins",
    )
    juices: List[IngredientFilterModel10] = Field(
        ..., description="The cocktail ingredient filters for searching against juices"
    )
    dilutions: List[IngredientFilterModel11] = Field(
        ...,
        description="The cocktail ingredient filters for searching against dilutions",
    )
    beerWineChampagne: List[IngredientFilterModel12] = Field(
        ...,
        description="The cocktail ingredient filters for searching against beers, wines and champagnes",
    )
    eras: List[IngredientFilterModel13] = Field(
        ...,
        description="The cocktail ingredient filters for searching against eras when cocktails were established",
    )


class IngredientModel(BaseModel):
    name: str = Field(..., description="The name of the ingredient", examples=["Gin"])
    uoM: UofMTypeModel
    requirement: IngredientRequirementTypeModel
    display: str = Field(
        ...,
        description="Gets the complete display value for the ingredient including units and measurments",
        examples=["1 1/2 ounces gin"],
    )
    units: float = Field(
        ...,
        description="The number of units to use in relation to the UoM (unit of measure) in the cocktail recipe",
        examples=[1.5],
    )
    preparation: PreparationTypeModel
    suggestions: str = Field(
        ...,
        description="Suggestion when using this ingredient",
        examples=["Preferably Plymouth"],
    )
    types: List[IngredientTypeModel] = Field(
        ...,
        description="The ingredient types that this ingredient is in relation to the cocktail recipe",
        examples=[["bitters", "spirit"]],
    )
    applications: List[IngredientApplicationModel] = Field(
        ...,
        description="The ingredient applications that this ingredient is in relation to the cocktail recipe",
        examples=[["base", "garnishment"]],
    )


class ManageFavoriteCocktailsRq(BaseModel):
    cocktailActions: List[CocktailFavoriteActionModel]


class CocktailModel(BaseModel):
    """
    The cocktail recipe model
    """

    id: str = Field(
        ...,
        description="The cocktail recipe unique identifier",
        examples=["clover-club"],
    )
    title: str = Field(..., description="The name of the cocktail recipe", examples=["Clover Club"])
    descriptiveTitle: str = Field(
        ...,
        description="A more descriptive title for the cocktail recipe, generally used as an editorial title",
        examples=["Clover Club: A Pink-Hued Classic"],
    )
    description: str = Field(
        ...,
        description="A brief editorial description for the cocktail recipe",
        examples=[
            "A classic pre-Prohibition cocktail made with gin, raspberry syrup, lemon juice, and egg white. Named after a Philadelphia men's club, it's a smooth, frothy, and slightly tart cocktail."
        ],
    )
    content: str = Field(
        ...,
        description="The complete descriptive cocktail recipe including ingredients, directions and historical information in markdown format",
        examples=["--markdown content--"],
    )
    publishedOn: AwareDatetime = Field(
        ...,
        description="The date this cocktail recipe was published on Cezzis.Com",
        examples=["2024-05-24T00:00:00-07:00"],
    )
    modifiedOn: AwareDatetime = Field(
        ...,
        description="The date this cocktail recipe was last modified on Cezzis.Com",
        examples=["2024-05-24T00:00:00-07:00"],
    )
    serves: int = Field(..., description="The number of people the cocktail recipe serves", examples=[1])
    prepTimeMinutes: int = Field(
        ...,
        description="The average number of minutes to build the cocktail using this recipe",
        examples=[5],
    )
    isIba: bool = Field(
        ...,
        description="Whether or not the cocktail represented by this recipe is recognized by the International Bartenders Association",
        examples=[True],
    )
    mainImages: List[CocktailImageModel] = Field(..., description="A list of primary images for the cocktail recipe")
    searchTiles: List[CocktailImageModel2] = Field(
        ...,
        description="A list of secondary, smaller sized images for the cocktail recipe",
    )
    glassware: List[GlasswareTypeModel] = Field(
        ...,
        description="The recommended glassware to use when serving the cocktail",
        examples=[["coupe", "cocktailGlass"]],
    )
    rating: CocktailRatingModel
    searchableTitles: List[str] = Field(
        ...,
        description="A list of titles that are queried against when issuing cocktail recipe search queries",
        examples=[["Clover Club", "Clover Club: A Pink-Hued Classic"]],
    )
    tags: List[str] = Field(
        ...,
        description="A list of taxonomy tags defining the cocktail recipe",
        examples=[["Traditional"]],
    )
    ingredients: List[IngredientModel] = Field(
        ..., description="The list of ingredients that make up the cocktail recipe"
    )
    instructions: List[InstructionStepModel] = Field(
        ..., description="The list of instructions to make the cocktail recipe"
    )


class CocktailRs(BaseModel):
    item: CocktailModel


class CocktailsListModel(BaseModel):
    id: str = Field(
        ...,
        description="The cocktail recipe unique identifier",
        examples=["clover-club"],
    )
    title: str = Field(..., description="The name of the cocktail recipe", examples=["Clover Club"])
    descriptiveTitle: str = Field(
        ...,
        description="A more descriptive title for the cocktail recipe, generally used as an editorial title",
        examples=["Clover Club: A Pink-Hued Classic"],
    )
    rating: float = Field(..., description="The overral rating for the recipe", examples=["3.5"])
    ingredients: List[IngredientModel] = Field(
        ..., description="The list of ingredients that make up the cocktail recipe"
    )
    isIba: bool = Field(
        ...,
        description="Whether or not the cocktail represented by this recipe is recognized by the International Bartenders Association",
        examples=[True],
    )
    serves: int = Field(..., description="The number of people the cocktail recipe serves", examples=[1])
    prepTimeMinutes: int = Field(
        ...,
        description="The average number of minutes to build the cocktail using this recipe",
        examples=[5],
    )
    mainImages: List[str] = Field(
        ...,
        description="A list of primary image uris for the cocktail recipe",
        examples=[["https://cdn.cezzis.com/cocktails/traditional-clover-club-cocktail-main.webp"]],
    )
    searchTiles: List[str] = Field(
        ...,
        description="A list of secondary, smaller sized image uris for the cocktail recipe",
        examples=[["https://cdn.cezzis.com/cocktails/traditional-clover-club-cocktail-300x300.webp"]],
    )
    glassware: List[GlasswareTypeModel] = Field(
        ...,
        description="The recommended glassware to use when serving the cocktail",
        examples=[["coupe", "cocktailGlass"]],
    )


class CocktailsListRs(BaseModel):
    items: List[CocktailsListModel] = Field(..., description="A list of cocktail recipe list models")
