# generated by datamodel-codegen:
#   filename:  http://cezzis-cocktailsapi.127.0.0.1.sslip.io/scalar/v1/openapi.json
#   timestamp: 2026-07-01T21:25:44+00:00

from __future__ import annotations

from enum import Enum
from typing import Dict, List, Optional

from pydantic import AwareDatetime, BaseModel, Field


class CocktailDietaryModel(BaseModel):
    """
    The computed dietary suitability for the cocktail recipe. Null when no ingredient supplies a dietary profile.
    """

    isVegan: bool = Field(
        ...,
        description="Whether the cocktail contains no animal-derived products",
        examples=[True],
    )
    isVegetarian: bool = Field(
        ...,
        description="Whether the cocktail is free of meat, poultry, and fish (dairy, egg, and honey are permitted)",
        examples=[True],
    )
    isDairyFree: bool = Field(
        ...,
        description="Whether the cocktail contains no milk-derived products",
        examples=[True],
    )
    isGlutenFree: bool = Field(
        ...,
        description="Whether the cocktail contains no gluten (distilled spirits qualify; malt and wheat-based products do not)",
        examples=[True],
    )
    isNutFree: bool = Field(
        ...,
        description="Whether the cocktail contains no tree nuts or peanuts",
        examples=[True],
    )
    isComplete: bool = Field(
        ...,
        description="Whether every ingredient supplied a dietary profile. When false the flags are partial and may overstate suitability",
        examples=[True],
    )


class CocktailImageModel(BaseModel):
    type: str = Field(..., description="The type of image variant", examples=["main"])
    uri: str = Field(
        ...,
        description="The uri of the image",
        examples=["https://cdn.cezzis.com/cocktails/traditional-clover-club-cocktail-main.webp"],
    )
    width: int = Field(..., description="The width of the image", examples=[800])
    height: int = Field(..., description="The height of the image", examples=[533])


class CocktailKeywordsModel(BaseModel):
    """
    The keywords associated with the cocktail recipe
    """

    keywordsBaseSpirit: List[str] = Field(..., description="Base spirit keywords")
    keywordsSpiritSubtype: List[str] = Field(..., description="Spirits subtype keywords")
    keywordsFlavorProfile: List[str] = Field(..., description="Flavor profile keywords")
    keywordsCocktailFamily: List[str] = Field(..., description="Cocktail family keywords")
    keywordsTechnique: List[str] = Field(..., description="Technique keywords")
    keywordsStrength: str = Field(..., description="Strength keyword")
    keywordsTemperature: str = Field(..., description="Temperature keyword")
    keywordsSeason: List[str] = Field(..., description="Season keywords")
    keywordsOccasion: List[str] = Field(..., description="Occasion keywords")
    keywordsMood: List[str] = Field(..., description="Mood keywords")
    keywordsSearchTerms: List[str] = Field(..., description="Search terms keywords")


class CocktailNutritionModel(BaseModel):
    """
    The estimated nutrition totals for the cocktail recipe. Null when no ingredient supplies nutrition data.
    """

    servingVolumeMl: float = Field(
        ...,
        description="The total liquid volume in milliliters the nutrition was computed from, when known",
        examples=[105],
    )
    calories: float = Field(..., description="The estimated total energy in kilocalories", examples=[194])
    carbohydrateContent: float = Field(
        ...,
        description="The estimated total carbohydrate content in grams",
        examples=[15],
    )
    sugarContent: float = Field(..., description="The estimated total sugar content in grams", examples=[14.5])
    fatContent: float = Field(..., description="The estimated total fat content in grams", examples=[0])
    saturatedFatContent: float = Field(
        ...,
        description="The estimated total saturated fat content in grams",
        examples=[0],
    )
    proteinContent: float = Field(..., description="The estimated total protein content in grams", examples=[0.3])
    fiberContent: float = Field(
        ...,
        description="The estimated total dietary fiber content in grams",
        examples=[0.2],
    )
    sodiumContent: float = Field(
        ...,
        description="The estimated total sodium content in milligrams",
        examples=[3],
    )
    isEstimated: bool = Field(
        ...,
        description="Whether any contributing value is estimated rather than measured. When true, present these figures as estimates",
        examples=[True],
    )
    isComplete: bool = Field(
        ...,
        description="Whether every ingredient supplied nutrition data. When false the totals are partial and understate the true values",
        examples=[True],
    )


class CocktailRatingModel(BaseModel):
    """
    A ratings for this cocktail
    """

    oneStars: int = Field(..., description="The number of one star ratings", examples=["5"])
    twoStars: int = Field(..., description="The number of two star ratings", examples=["1"])
    threeStars: int = Field(..., description="The number of three star ratings", examples=["1"])
    fourStars: int = Field(..., description="The number of four star ratings", examples=["1"])
    fiveStars: int = Field(..., description="The number of five star ratings", examples=["1"])
    totalStars: int = Field(..., description="The total number of stars given", examples=["1"])
    rating: float = Field(..., description="The actual overal rating", examples=["3.5"])
    ratingCount: int = Field(..., description="The total number of ratings given", examples=["1"])


class CocktailSearchImageModel(BaseModel):
    type: str = Field(..., description="Type of the image", examples=["search-tile"])
    uri: str = Field(
        ...,
        description="URI of the image",
        examples=["https://cdn.cezzis.com/cocktails/traditional-clover-club-cocktail-main.webp"],
    )
    width: int = Field(..., description="Width of the image in pixels", examples=[300])
    height: int = Field(..., description="Height of the image in pixels", examples=[300])


class CocktailVectorSearchResultModel(BaseModel):
    score: float = Field(..., description="Score of the search result", examples=[0.5158496])


class CollectionVisibilityTypeModel(Enum):
    """
    The collection visibility type
    """

    always = "always"
    holiday = "holiday"
    season = "season"


class GlasswareTypeModel(Enum):
    none = "none"
    rocks = "rocks"
    highball = "highball"
    shotGlass = "shotGlass"
    coupe = "coupe"
    copperMug = "copperMug"
    collins = "collins"
    cocktailGlass = "cocktailGlass"
    wineGlass = "wineGlass"
    flute = "flute"
    lowball = "lowball"
    fizz = "fizz"
    tikiMug = "tikiMug"
    pintGlass = "pintGlass"
    julepTin = "julepTin"
    doubleRocks = "doubleRocks"
    hurricane = "hurricane"
    hollowedPineapple = "hollowedPineapple"
    snifter = "snifter"
    scorpionBowl = "scorpionBowl"
    nickAndNora = "nickAndNora"
    toddy = "toddy"
    pilsner = "pilsner"
    sling = "sling"
    goblet = "goblet"
    cantaritosClayPot = "cantaritosClayPot"
    martini = "martini"


class IngredientApplicationModel(Enum):
    base = "base"
    additional = "additional"
    garnishment = "garnishment"
    muddle = "muddle"


class IngredientFilterModel(BaseModel):
    id: str = Field(..., description="The filter identifier", examples=["classification-name"])
    name: str = Field(..., description="The display name of the filter", examples=["Name Of Filter"])
    parentId: str = Field(..., description="The parent ingredient", examples=["tequila"])
    used: Optional[bool] = Field(
        None,
        description="Whether the ingredient is used directly in a cocktail recipe. Null implies used.",
        examples=[False],
    )


class IngredientRequirementTypeModel(Enum):
    """
    Whether or not this ingredient is required ('Required' or 'Optional')
    """

    none = "none"
    optional = "optional"
    required = "required"


class IngredientRequirementTypeModel2(Enum):
    """
    Requirement type for the ingredient
    """

    none = "none"
    optional = "optional"
    required = "required"


class IngredientVariationModel(BaseModel):
    id: str = Field(..., description="The ingredient variation identifier", examples=["bourbon"])
    name: str = Field(..., description="The ingredient variation name", examples=["Bourbon"])
    applications: List[IngredientApplicationModel] = Field(
        ...,
        description="The applications this ingredient variation can be used as",
        examples=["base"],
    )


class InstructionStepModel(BaseModel):
    display: str = Field(
        ...,
        description="The displayable value for the instruction step",
        examples=[
            "Combine the gin, lemon juice, raspberry syrup, and egg white in a shaker without ice and dry shake (shake without ice) for about 10 seconds to make the foam."
        ],
    )
    order: int = Field(
        ...,
        description="The order of the instruction step in which it should be performed",
        examples=[1],
    )


class NullableOfCollectionHolidayTypeModel(Enum):
    """
    The holiday rule for a holiday collection
    """

    newYears = "newYears"
    valentinesDay = "valentinesDay"
    stPatricksDay = "stPatricksDay"
    cincoDeMayo = "cincoDeMayo"
    easter = "easter"
    memorialDay = "memorialDay"
    fourthOfJuly = "fourthOfJuly"
    laborDay = "laborDay"
    halloween = "halloween"
    thanksgiving = "thanksgiving"
    christmas = "christmas"
    dayOfTheDead = "dayOfTheDead"
    mothersDay = "mothersDay"
    fathersDay = "fathersDay"
    NoneType_None = None


class NullableOfCollectionSeasonTypeModel(Enum):
    """
    The season rule for a seasonal collection
    """

    spring = "spring"
    summer = "summer"
    fall = "fall"
    winter = "winter"
    NoneType_None = None


class PreparationTypeModel(Enum):
    """
    Any preparation that should be made with this ingredient
    """

    none = "none"
    chilled = "chilled"
    freshlySqueezed = "freshlySqueezed"
    peeledAndJuiced = "peeledAndJuiced"
    freshlyGrated = "freshlyGrated"
    quartered = "quartered"
    freshPressed = "freshPressed"


class PreparationTypeModel2(Enum):
    """
    Preparation type for the ingredient
    """

    none = "none"
    chilled = "chilled"
    freshlySqueezed = "freshlySqueezed"
    peeledAndJuiced = "peeledAndJuiced"
    freshlyGrated = "freshlyGrated"
    quartered = "quartered"
    freshPressed = "freshPressed"


class ProblemDetails(BaseModel):
    type: Optional[str] = None
    title: Optional[str] = None
    status: Optional[int] = None
    detail: Optional[str] = None
    instance: Optional[str] = None


class PublishCocktailsRq(BaseModel):
    cocktailIds: List[str] = Field(
        ...,
        description="A list of cocktail IDs to publish",
        examples=[["pegu-club", "aperol-spritz", "margarita"]],
    )


class PublishIngredientsRq(BaseModel):
    ingredientIds: List[str] = Field(
        ...,
        description="A list of ingredient IDs to publish. Empty means publish all ingredients",
        examples=[["gin", "cointreau", "lemon-juice"]],
    )


class TaxonomyFilterTypeModel(Enum):
    """
    The ingredient filter group used for cocktail search filters
    """

    none = "none"
    spirits = "spirits"
    liqueursAperitifsAndAmari = "liqueursAperitifsAndAmari"
    wineBeerAndSake = "wineBeerAndSake"
    juicesAndPurees = "juicesAndPurees"
    fruitsAndCitrus = "fruitsAndCitrus"
    vegetablesAndSavoryProduce = "vegetablesAndSavoryProduce"
    aromaticsTeaAndCoffee = "aromaticsTeaAndCoffee"
    sweetenersAndSyrups = "sweetenersAndSyrups"
    savoryBrinyAndHeat = "savoryBrinyAndHeat"
    bitters = "bitters"
    dairyAndEggs = "dairyAndEggs"
    mixersSodaAndWater = "mixersSodaAndWater"


class UofMTypeModel(Enum):
    """
    The unit of measure when using this ingredient in a cocktail recipe
    """

    none = "none"
    ounces = "ounces"
    dashes = "dashes"
    tablespoon = "tablespoon"
    topoff = "topoff"
    item = "item"
    teaspoon = "teaspoon"
    toTaste = "toTaste"
    barspoon = "barspoon"
    cups = "cups"
    splash = "splash"
    discretion = "discretion"
    pinch = "pinch"


class UofMTypeModel2(Enum):
    """
    Unit of Measure for the ingredient
    """

    none = "none"
    ounces = "ounces"
    dashes = "dashes"
    tablespoon = "tablespoon"
    topoff = "topoff"
    item = "item"
    teaspoon = "teaspoon"
    toTaste = "toTaste"
    barspoon = "barspoon"
    cups = "cups"
    splash = "splash"
    discretion = "discretion"
    pinch = "pinch"


class CocktailCollectionListModel(BaseModel):
    id: str = Field(..., description="The cocktail collection identifier")
    title: str = Field(..., description="The cocktail collection title")
    shortTitle: str = Field(..., description="The short collection title for compact displays")
    description: str = Field(..., description="The cocktail collection description")
    intro: str = Field(..., description="The collection intro text for the landing page")
    imageUrl: str = Field(..., description="The collection image URL")
    iconSvg: str = Field(..., description="The collection icon SVG")
    order: int = Field(..., description="The display order of the collection")
    visibility: CollectionVisibilityTypeModel
    season: NullableOfCollectionSeasonTypeModel
    holiday: NullableOfCollectionHolidayTypeModel
    relatedCollectionIds: List[str] = Field(..., description="The related collection identifiers")


class CocktailCollectionModel(BaseModel):
    """
    The cocktail collection model
    """

    id: str = Field(..., description="The cocktail collection identifier")
    title: str = Field(..., description="The cocktail collection title")
    shortTitle: str = Field(..., description="The short collection title for compact displays")
    description: str = Field(..., description="The cocktail collection description")
    intro: str = Field(..., description="The collection intro text for the landing page")
    imageUrl: str = Field(..., description="The collection image URL")
    iconSvg: str = Field(..., description="The collection icon SVG")
    order: int = Field(..., description="The display order of the collection")
    visibility: CollectionVisibilityTypeModel
    season: NullableOfCollectionSeasonTypeModel
    holiday: NullableOfCollectionHolidayTypeModel
    relatedCollectionIds: List[str] = Field(..., description="The related collection identifiers")
    cocktailIds: List[str] = Field(..., description="The cocktail identifiers in the collection")


class CocktailCollectionRs(BaseModel):
    item: CocktailCollectionModel


class CocktailCollectionsRs(BaseModel):
    items: List[CocktailCollectionListModel] = Field(..., description="The visible cocktail collections")


class CocktailIngredientFiltersRs(BaseModel):
    spirits: List[IngredientFilterModel] = Field(
        ..., description="The cocktail ingredient filters for searching against spirits"
    )
    liqueursAperitifsAndAmari: List = Field(
        ...,
        description="The cocktail ingredient filters for searching against liqueurs, aperitifs, and amari",
    )
    wineBeerAndSake: List = Field(
        ...,
        description="The cocktail ingredient filters for searching against wine, beer, and sake ingredients",
    )
    juicesAndPurees: List = Field(
        ...,
        description="The cocktail ingredient filters for searching against juices and purees",
    )
    fruitsAndCitrus: List = Field(
        ...,
        description="The cocktail ingredient filters for searching against fruits and citrus",
    )
    vegetablesAndSavoryProduce: List = Field(
        ...,
        description="The cocktail ingredient filters for searching against vegetables and savory produce",
    )
    aromaticsTeaAndCoffee: List = Field(
        ...,
        description="The cocktail ingredient filters for searching against aromatics, tea, and coffee",
    )
    sweetenersAndSyrups: List = Field(
        ...,
        description="The cocktail ingredient filters for searching against sweeteners and syrups",
    )
    savoryBrinyAndHeat: List = Field(
        ...,
        description="The cocktail ingredient filters for searching against savory, briny, and heat ingredients",
    )
    bitters: List = Field(..., description="The cocktail ingredient filters for searching against bitters")
    dairyAndEggs: List = Field(
        ...,
        description="The cocktail ingredient filters for searching against dairy and eggs",
    )
    mixersSodaAndWater: List = Field(
        ...,
        description="The cocktail ingredient filters for searching against mixers, soda, and water",
    )
    eras: List = Field(
        ...,
        description="The cocktail ingredient filters for searching against eras when cocktails were established",
    )


class CocktailSearchIngredientModel(BaseModel):
    id: str = Field(
        ...,
        description="Unique identifier for the ingredient",
        examples=["blanco-tequila"],
    )
    name: str = Field(..., description="Name of the ingredient", examples=["Blanco Tequila"])
    uoM: UofMTypeModel2
    requirement: IngredientRequirementTypeModel2
    display: str = Field(
        ...,
        description="Display string for the ingredient",
        examples=["1 1/2 oz Blanco Tequila"],
    )
    units: float = Field(..., description="Quantity of the ingredient", examples=[1.5])
    preparation: PreparationTypeModel2
    suggestions: str = Field(
        ...,
        description="Suggestions for the ingredient",
        examples=["Use a good quality Blanco Tequila for the best flavor"],
    )
    types: List[str] = Field(..., description="List of ingredient types", examples=["spirit"])
    applications: List[IngredientApplicationModel] = Field(
        ..., description="List of ingredient applications", examples=["base"]
    )


class CocktailSearchStatisticsModel(BaseModel):
    """
    Search statistics for the cocktail
    """

    totalScore: float = Field(..., description="Sum of all hit scores", examples=[0])
    maxScore: float = Field(..., description="Highest individual chunk score", examples=[0])
    avgScore: float = Field(..., description="Average score across all hits", examples=[0])
    weightedScore: float = Field(
        ...,
        description="Weighted score combining avg with hit count boost",
        examples=[0],
    )
    rerankerScore: float = Field(..., description="Cross-encoder reranker relevance score", examples=[0])
    hitCount: int = Field(..., description="Number of matching chunks", examples=[0])
    hitResults: List[CocktailVectorSearchResultModel] = Field(..., description="List of hit results with their scores")


class IngredientModel(BaseModel):
    id: str = Field(..., description="The cocktail ingredient unique identifier", examples=["gin"])
    name: str = Field(..., description="The name of the ingredient", examples=["Gin"])
    uoM: UofMTypeModel
    requirement: IngredientRequirementTypeModel
    display: str = Field(
        ...,
        description="Gets the complete display value for the ingredient including units and measurments",
        examples=["1 1/2 ounces gin"],
    )
    units: float = Field(
        ...,
        description="The number of units to use in relation to the UoM (unit of measure) in the cocktail recipe",
        examples=[1.5],
    )
    preparation: PreparationTypeModel
    suggestions: str = Field(
        ...,
        description="Suggestion when using this ingredient",
        examples=["Preferably Plymouth"],
    )
    types: List[str] = Field(
        ...,
        description="The ordered ingredient taxonomy from broad to specific",
        examples=[["spirits", "whiskey", "bourbon"]],
    )
    taxonomyFilterType: TaxonomyFilterTypeModel
    applications: List[IngredientApplicationModel] = Field(
        ...,
        description="The ingredient applications that this ingredient is in relation to the cocktail recipe",
        examples=[["base", "garnishment"]],
    )


class InventoryIngredientModel(BaseModel):
    """
    The ingredient model
    """

    id: str = Field(..., description="The ingredient identifier", examples=["gin"])
    parentId: str = Field(..., description="The parent ingredient identifier", examples=["gin"])
    name: str = Field(..., description="The ingredient name", examples=["London Dry Gin"])
    shelfDisplay: str = Field(
        ...,
        description="The ingredient shelf display name",
        examples=["London Dry Gin"],
    )
    types: List[str] = Field(
        ...,
        description="The ordered ingredient taxonomy from broad to specific",
        examples=[["spirits", "whiskey", "bourbon"]],
    )
    taxonomyFilterType: TaxonomyFilterTypeModel
    applications: List[IngredientApplicationModel] = Field(
        ..., description="The ingredient applications", examples=["base"]
    )
    variations: List[IngredientVariationModel] = Field(..., description="The ingredient variations")
    publishedOn: AwareDatetime = Field(
        ...,
        description="The date and time this ingredient was published",
        examples=["2025-04-22T20:09:40-06:00"],
    )


class InventoryIngredientModel2(BaseModel):
    id: str = Field(..., description="The ingredient identifier", examples=["gin"])
    parentId: str = Field(..., description="The parent ingredient identifier", examples=["gin"])
    name: str = Field(..., description="The ingredient name", examples=["London Dry Gin"])
    shelfDisplay: str = Field(
        ...,
        description="The ingredient shelf display name",
        examples=["London Dry Gin"],
    )
    types: List[str] = Field(
        ...,
        description="The ordered ingredient taxonomy from broad to specific",
        examples=[["spirits", "whiskey", "bourbon"]],
    )
    taxonomyFilterType: TaxonomyFilterTypeModel
    applications: List[IngredientApplicationModel] = Field(
        ..., description="The ingredient applications", examples=["base"]
    )
    variations: List[IngredientVariationModel] = Field(..., description="The ingredient variations")
    publishedOn: AwareDatetime = Field(
        ...,
        description="The date and time this ingredient was published",
        examples=["2025-04-22T20:09:40-06:00"],
    )


class CocktailIngredientMatchSearchModel(BaseModel):
    id: str = Field(
        ...,
        description="Unique identifier for the cocktail",
        examples=["old-fashioned"],
    )
    title: str = Field(..., description="Title of the cocktail", examples=["Old Fashioned"])
    descriptiveTitle: str = Field(
        ...,
        description="Descriptive title of the cocktail",
        examples=["The Old Fashioned: A Timeless Whiskey Cocktail"],
    )
    rating: float = Field(..., description="Rating of the cocktail", examples=[4.5])
    ingredients: List[CocktailSearchIngredientModel] = Field(..., description="List of ingredients in the cocktail")
    isIba: bool = Field(
        ...,
        description="Indicates if the cocktail is an IBA official cocktail",
        examples=[True],
    )
    serves: int = Field(..., description="Number of servings", examples=[1])
    prepTimeMinutes: int = Field(..., description="Preparation time in minutes", examples=[5])
    images: List[CocktailSearchImageModel] = Field(..., description="Images associated with the cocktail")
    glassware: List[GlasswareTypeModel] = Field(
        ...,
        description="List of glassware types used for the cocktail",
        examples=[["rocks", "coupe"]],
    )
    searchStatistics: CocktailSearchStatisticsModel
    unmatchedIngredientCount: int = Field(
        ...,
        description="The number of cocktail ingredients that were not present in the supplied ingredient list",
        examples=[2],
    )
    missingGarnishmentCount: int = Field(
        ...,
        description="The number of garnishment ingredients that were not present in the supplied ingredient list",
        examples=[1],
    )


class CocktailModel(BaseModel):
    """
    The cocktail recipe model
    """

    id: str = Field(
        ...,
        description="The cocktail recipe unique identifier",
        examples=["clover-club"],
    )
    title: str = Field(..., description="The name of the cocktail recipe", examples=["Clover Club"])
    descriptiveTitle: str = Field(
        ...,
        description="A more descriptive title for the cocktail recipe, generally used as an editorial title",
        examples=["Clover Club: A Pink-Hued Classic"],
    )
    description: str = Field(
        ...,
        description="A brief editorial description for the cocktail recipe",
        examples=[
            "A classic pre-Prohibition cocktail made with gin, raspberry syrup, lemon juice, and egg white. Named after a Philadelphia men's club, it's a smooth, frothy, and slightly tart cocktail."
        ],
    )
    content: str = Field(
        ...,
        description="The complete descriptive cocktail recipe including ingredients, directions and historical information in markdown format",
        examples=["--markdown content--"],
    )
    publishedOn: AwareDatetime = Field(
        ...,
        description="The date this cocktail recipe was published on Cezzis.Com",
        examples=["2024-05-24T00:00:00-07:00"],
    )
    modifiedOn: AwareDatetime = Field(
        ...,
        description="The date this cocktail recipe was last modified on Cezzis.Com",
        examples=["2024-05-24T00:00:00-07:00"],
    )
    serves: int = Field(..., description="The number of people the cocktail recipe serves", examples=[1])
    prepTimeMinutes: int = Field(
        ...,
        description="The average number of minutes to build the cocktail using this recipe",
        examples=[5],
    )
    isIba: bool = Field(
        ...,
        description="Whether or not the cocktail represented by this recipe is recognized by the International Bartenders Association",
        examples=[True],
    )
    images: List[CocktailImageModel] = Field(..., description="A list of images for the cocktail recipe")
    glassware: List[GlasswareTypeModel] = Field(
        ...,
        description="The recommended glassware to use when serving the cocktail",
        examples=[["coupe", "cocktailGlass"]],
    )
    rating: CocktailRatingModel
    reactions: Dict[str, int] = Field(
        ...,
        description="The summed user reaction totals for this cocktail keyed by reaction type",
    )
    searchableTitles: List[str] = Field(
        ...,
        description="A list of titles that are queried against when issuing cocktail recipe search queries",
        examples=[["Clover Club", "Clover Club: A Pink-Hued Classic"]],
    )
    tags: List[str] = Field(
        ...,
        description="A list of taxonomy tags defining the cocktail recipe",
        examples=[["Traditional"]],
    )
    ingredients: List[IngredientModel] = Field(
        ..., description="The list of ingredients that make up the cocktail recipe"
    )
    instructions: List[InstructionStepModel] = Field(
        ..., description="The list of instructions to make the cocktail recipe"
    )
    keywords: CocktailKeywordsModel
    recipeCuisine: str = Field(
        ...,
        description="The regional or national cuisine the cocktail recipe is associated with, aligned with schema.org Recipe.recipeCuisine. Empty when the origin cannot be determined.",
        examples=["American"],
    )
    collections: List[str] = Field(..., description="A list of collections that this cocktail recipe belongs to")
    nutrition: Optional[CocktailNutritionModel] = None
    dietary: Optional[CocktailDietaryModel] = None


class CocktailRs(BaseModel):
    item: CocktailModel


class CocktailSearchModel(BaseModel):
    id: str = Field(
        ...,
        description="Unique identifier for the cocktail",
        examples=["old-fashioned"],
    )
    title: str = Field(..., description="Title of the cocktail", examples=["Old Fashioned"])
    descriptiveTitle: str = Field(
        ...,
        description="Descriptive title of the cocktail",
        examples=["The Old Fashioned: A Timeless Whiskey Cocktail"],
    )
    rating: float = Field(..., description="Rating of the cocktail", examples=[4.5])
    ingredients: List[CocktailSearchIngredientModel] = Field(..., description="List of ingredients in the cocktail")
    isIba: bool = Field(
        ...,
        description="Indicates if the cocktail is an IBA official cocktail",
        examples=[True],
    )
    serves: int = Field(..., description="Number of servings", examples=[1])
    prepTimeMinutes: int = Field(..., description="Preparation time in minutes", examples=[5])
    images: List[CocktailSearchImageModel] = Field(..., description="Images associated with the cocktail")
    glassware: List[GlasswareTypeModel] = Field(
        ...,
        description="List of glassware types used for the cocktail",
        examples=[["rocks", "coupe"]],
    )
    searchStatistics: CocktailSearchStatisticsModel


class CocktailsIngredientMatchSearchRs(BaseModel):
    items: List[CocktailIngredientMatchSearchModel] = Field(
        ..., description="List of cocktails returned from ingredient-overlap search"
    )


class CocktailsRelationsRs(BaseModel):
    items: List[CocktailSearchModel] = Field(..., description="List of related cocktails returned from the search")


class CocktailsSearchRs(BaseModel):
    items: List[CocktailSearchModel] = Field(..., description="List of cocktails returned from the search")


class IngredientRs(BaseModel):
    item: InventoryIngredientModel


class IngredientsRs(BaseModel):
    skip: int = Field(
        ...,
        description="The number of items skipped from the start of the ingredient collection",
        examples=[0],
    )
    take: int = Field(
        ...,
        description="The number of items requested from the ingredient collection",
        examples=[20],
    )
    items: List[InventoryIngredientModel2] = Field(..., description="The paged ingredient list")
