apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - configmap.yml
  - external-secrets.yml
  - deployment.yml
images:
  - name: acrveceusgloshared001.azurecr.io/cocktailsingestionchunkingagent
    newTag: 0.0.49
    newName: acrveceusgloshared001.azurecr.io/cocktailsingestionchunkingagent
